Home responsive: SideDrawer Menu was added
elinaKM/petfinder pull request #3
Opened 2020-06-23 08:05 UTC by elinaKM

2020-06-23 19:22 UTC, okvv requested changes

2020-06-23 19:22 UTC, okvv commented on src/components/Header.js
> +const Header = ({ setShowMenu }) => (
what's that?
maybe isMenuHidden? toggleMenuVisibility?

2020-06-23 19:22 UTC, okvv commented on src/components/sideMenu/SideDrawerMenu.js
> +const SideDrawerMenu = ({open, onCloseMenu}) => (
isOpen

2020-06-23 19:22 UTC, okvv commented on src/pages/Home.js
> +    const [showMenu, setShowMenu] = useState(false);
isMenuVisible?

2020-06-23 19:22 UTC, okvv commented on src/pages/Home.js
> +    const [showMenu, setShowMenu] = useState(false);
toggleMenuVisiblity? / toggleMenu?

2020-06-23 19:22 UTC, okvv commented on src/components/sideMenu/SideDrawerMenu.js
> +        <SideMenuCloseControl onClick = {onCloseMenu}/>
what happens onClick? closeMenu? or toggleMenu?
try to read the code like a conversation

2020-06-23 19:22 UTC, okvv commented on src/components/header/HamMenuControl.js
> +  <Wrapper onClick={onClick}>
onClick={clickHandler } to prevent confusion

2020-06-23 19:22 UTC, okvv commented on src/components/common/Backdrop.js
> +const Backdrop = ({onClick}) => <Wrapper onClick={onClick}/>
onClick={clickHandler } to prevent confusion

2020-06-23 19:22 UTC, okvv commented on src/components/Wellcome.js
> +const Wellcome = ({ setShowMenu }) => (
toggleMenuVisibility

2020-06-25 08:45 UTC, elinaKM commented on src/pages/Home.js
> +    const [showMenu, setShowMenu] = useState(false);
done

2020-06-25 08:46 UTC, elinaKM commented on src/components/sideMenu/SideDrawerMenu.js
> +const SideDrawerMenu = ({open, onCloseMenu}) => (
done

2020-06-27 21:20 UTC, okvv commented on src/components/common/Backdrop.js
> +const Backdrop = ({clickHandler }) => <Wrapper onClick={clickHandler }/>
too general

2020-06-27 21:24 UTC, okvv commented on src/components/Wellcome.js
> +                    This site is a perfect place to find a perfect pet.<br />
FYI: you can make a new component and pass text as a reference
anyway I don't think BR scales well on multiple screen and with any length of text

2020-06-27 21:45 UTC, okvv commented on src/pages/Home.js
> +            <SideDrawerMenu isOpen={isMenuVisible} onCloseMenu={() => setMenuVisible(false)}/>
as long as you're aware of the rendering costs of passing functions like this it's ok

2020-06-27 21:45 UTC, okvv approved these changes
please read comments

2020-06-28 12:34 UTC, okvv commented on src/pages/Home.js
> +            { isMenuVisible && <Backdrop clickHandler ={sideDrawerCloseHandler}/>}
space

2020-06-28 12:34 UTC, okvv approved these changes

2020-06-28 12:35 UTC, okvv commented
review comment and merge

2020-06-28 12:47 UTC, elinaKM commented
merge

2020-06-28 12:48 UTC, merged