Pet page - basic page was added, Router structure was fixed in order make header and footer available from each page
elinaKM/petfinder pull request #6
Opened 2020-07-01 08:01 UTC by elinaKM

2020-07-02 17:39 UTC, elinaKM commented on src/App.js
> +          <PetPage path="petfinder/pets/:petId" />
עבירי סטרינגים של ניווט לקבועים

2020-07-05 07:06 UTC, okvv requested changes

2020-07-05 07:06 UTC, okvv commented on src/components/Wellcome.js
> +                    Pick one. Save one live. Find a new love.
why not another <text> instead of BR?

2020-07-05 07:06 UTC, okvv commented on src/components/common/InputWithLabel.js
> +import React from 'react'
LabledInput?

2020-07-05 07:06 UTC, okvv commented on src/components/common/TextAreaWithLabel.js
> +import React from 'react'
LabledTextArea?

2020-07-05 07:06 UTC, okvv commented on src/pages/PetPage.js
> +    const {imgs, name, breed, location, age, gender, size, color, aboutInfo, org} = petsDB[props.petId];
add defaults or it'll crash

2020-07-05 11:42 UTC, elinaKM commented on src/components/common/InputWithLabel.js
> +import React from 'react'
done

2020-07-05 11:42 UTC, elinaKM commented on src/App.js
> +          <PetPage path="petfinder/pets/:petId" />
done

2020-07-05 11:42 UTC, elinaKM commented on src/components/common/TextAreaWithLabel.js
> +import React from 'react'
done

2020-07-05 12:08 UTC, elinaKM commented on src/components/Wellcome.js
> +                    Pick one. Save one live. Find a new love.
done

2020-07-05 12:08 UTC, elinaKM commented on src/pages/PetPage.js
> +    const {imgs, name, breed, location, age, gender, size, color, aboutInfo, org} = petsDB[props.petId];
done

2020-07-05 12:37 UTC, merged